<?php echo $this->doctype(); ?>






<html lang="en" xmlns="http://www.w3.org/1999/xhtml">


 


    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/hostclipse.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

  
    
     <!--script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js"-->
<script>
$(function()
{ 
    $(":input").blur(function()
    {
        var formElementId = $(this).get(0).id;
      
        //console.log(formElementId);
        doValidation(formElementId);
       
    });
    $("form").submit(function () 
   { 
        doValidation();
   	   
    
 });});

function count(obj) { return Object.keys(obj).length; }


 function doValidation(id){
	 var url = '/resident/validateform';
	 var data = {};//tell browser we are dealing with a json object
	 var hasErrors = false;
     $("input").each(function()
     {
         
   	 data[$(this).attr('name')] = $(this).val(); 	    
     });
     
     console.log(data);
	 $.post(url,data,function(resp)
	{
		 console.log(count(resp));
		 if (count(resp)>0)
			 hasErrors = true;
		 if (!hasErrors){
			    console.log("all clear");
				 return true;//all clear
		 }
		 if ( id != null){//blur event
		 $("#"+id).parent().parent().find('.errors').remove();
		 $("#"+id).parent().parent().append(getErrorHtml(resp[id], id));
		 //$("#"+id).parent().append("error");
		 }else //submit event, validate whole form
		 {
			 $("input").each(function()
				     {
				     inputId = $(this).attr('id');
				     errorMsgs = resp[inputId];
				     $("#"+ inputId).parent().parent().find('.errors').remove();
					 $("#"+ inputId).parent().parent().append(getErrorHtml(errorMsgs, inputId));
				         
				     });
		     return false;

		 }
	},'json');   


 }

 
 function getErrorHtml(formErrors, id)
 {
	  var o = '<ul id="errors-'+id+'" class="errors">';
	  for ( errorKey in formErrors)
	  {
		 
		  o+='<li>' + formErrors[errorKey] + '</li>';

		  } 
	  o+='</ul>';
	  console.log(o);
	  return o;
 }
	  
</script>

    
    
    
    </head>
    

    <body>
    <div id="register_number_div">
    </div>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Skeleton Application') ?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
